name: 'Terraform S3 Bucket Deployment (IAM Role)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write   # Required for OIDC token
  contents: read    # Required to checkout code

env:
  TF_VERSION: '1.6.6'
  AWS_REGION: 'us-east-1'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials using IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-S3-Role
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActions-Terraform-Session

    - name: Verify AWS Identity
      run: |
        echo "Current AWS Identity:"
        aws sts get-caller-identity
        echo "Available S3 buckets:"
        aws s3 ls

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        terraform plan -input=false \
          -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
          -var="environment=prod" \
          -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan

    - name: Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform output

    - name: Upload files to S3 (if bucket created)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Upload any HTML files to the bucket
        if [ -f "terraform-flow-diagram.html" ]; then
          aws s3 cp terraform-flow-diagram.html s3://${{ secrets.S3_BUCKET_NAME }}/ --content-type "text/html"
        fi
        if [ -f "index.html" ]; then
          aws s3 cp index.html s3://${{ secrets.S3_BUCKET_NAME }}/ --content-type "text/html"
        fi
